services:
  web:
    build: .
    container_name: cancer-prediction-web
    command: gunicorn Capstone.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 180
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: cancer-prediction-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - web
    networks:
      - app-network

# https 인증서 발급
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email luca0328@pusan.ac.kr -d esctabularpredict.xyz --agree-tos --non-interactive --force-renewal

volumes:
  static_volume:
  certs:
  certbot-www:

networks:
  app-network:
    driver: bridge
